# pylint: disable=missing-module-docstring, missing-function-docstring, missing-class-docstring
import os


ENV_LAMBDA_MULESOFT_CLIENT_ID = "MULESOFT_CLIENT_ID"
ENV_LAMBDA_MULESOFT_CLIENT_SECRET = "MULESOFT_CLIENT_SECRET"
ENV_LAMBDA_MULESOFT_USERNAME = "MULESOFT_USERNAME"
ENV_LAMBDA_MULESOFT_PASSWORD = "MULESOFT_PASSWORD"
ENV_LAMBDA_MULESOFT_OUTREACH_ENDPOINT = "MULESOFT_OUTREACH_ENDPOINT"
ENV_LAMBDA_MULESOFT_POPUP_ENDPOINT = "MULESOFT_POPUP_ENDPOINT"
ENV_LAMBDA_MULESOFT_CUSTOMER_ACCOUNT_ENDPOINT = "MULESOFT_CUSTOMER_ACCOUNT_ENDPOINT"
ENV_STRATEGY_TABLE_NAME = "STRATEGY_TABLE_NAME"
